---
    - name: Installing docker in the agent using ansible playbook
      become: yes
      connection: ssh
      hosts: All-Slave
      vars_files: 
          - vars/default.yaml

      tasks:
              - name: Install aptitude using apt
                apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

              - name: install required system packages
                apt: name={{item}} state=latest update_cache=yes
                loop: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

              - name: Add docker GPG apt key
                apt_key:
                    url: https://download.docker.com/linux/ubuntu/gpg
                    state: present

              - name: Add docker repository
                apt_repository: 
                    repo: deb https://download.docker.com/linux/ubuntu bionic stable
                    state: present

              - name: Upadte apt and install docker-ce
                apt: update_cache=yes name=docker-ce state=latest

              - name: Install docker module for python
                pip: 
                    name: docker

              - name: pull default docker image
                docker_image:
                    name: "{{container_image}}"
                    source: pull

              - name: Create default containers
                docker_container:
                    name: "{{container_name}}{{item}}"
                    image: "{{container_image}}"
                    command: "{{container_command}}"
                    state: present
                with_sequence: count={{ containers }}
